services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgres://postgres:Ilovedu20%40@localhost:5432/DATABASE?schema=student_gpa
      ML_API_URL: http://host.docker.internal:8000  

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
